name: 'Build Datasheet'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.14.1
      - name: Run Tectonic
        run:  tectonic datasheet/datasheet.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: datasheet.pdf
